### ISSUE TITLE
The kernel size of SCNN

### ISSUE THREAD

**Issue by cfzd** [XingangPan/SCNN#1]
Hi, I'm little confused about the kernel size used in the SCNN_DURL network. In the paper, the kernel size is set to C x W where C and W are the number of channel and kernel width respectively. But in the Lua code I find that the kernel size is set to  W x 1 or 1 x W according to the directions.  What's the difference between these two kind of kernels?

**Comment by XingangPan** [comment]
Hi, sorry to reply late. This is just a difference of denotation. In the paper we view the convolution as 2d-conv, thus the dimension of size 1 is omitted. However the implementation is done in a 3d manner, so the '1' should be preserved. Hope this would be helpful to you.

**Comment by serenmonky** [comment]
<a href="https://ver-indianajonesyeldialdeldestino.statuspage.io/">Indiana Jones y el Dial del Destino Película Completa</a>
<a href="https://mirarubyaventurasdeunakrakenadolescente.statuspage.io/">Ruby: Aventuras de una kraken adolescente Película Completa</a>
<a href="https://cuevana3misionimposiblesentenciamortalparteuno.statuspage.io/">Misión: Imposible - Sentencia Mortal (Parte Uno) Película Completa</a>
<a href="https://pelisplusverelemental.statuspage.io/">Elemental Película Completa</a>
<a href="https://verbarbie.statuspage.io/">Barbie Película Completa</a>
<a href="https://cuevana3veroppenheimer.statuspage.io/">Oppenheimer Película Completa</a>
<a href="https://pelisplusvermegalodon2lafosa.statuspage.io/">Megalodón 2: La fosa Película Completa</a>
<a href="https://pelisplusverfivenightsatfreddys.statuspage.io/">Five Nights at Freddy's Película Completa</a>
<a href="https://pelisplusverinsidiouslapuertaroja.statuspage.io/">Insidious: La puerta roja Película Completa</a>
<a href="https://vervacacionesdeverano.statuspage.io/">Vacaciones de verano Película Completa</a>
<a href="https://bit.ly/3NL29NN">BLOGSPOT</a>
<a href="https://bit.ly/3O6ATek">BLOGSPOT</a>
<a href="https://bit.ly/3PP6bYi">BLOGSPOT</a>
<a href="https://bit.ly/3XGhV1h">BLOGSPOT</a>
<a href="https://bit.ly/3POcqM4">BLOGSPOT</a>
<a href="https://bit.ly/3O31l8q">BLOGSPOT</a>
<a href="https://bit.ly/3O8vXFS">BLOGSPOT</a>
<a href="https://bit.ly/3JOHtDC">BLOGSPOT</a>
<a href="https://bit.ly/3POpX63">BLOGSPOT</a>
<a href="https://bit.ly/3POqcht">BLOGSPOT</a>
<a href="https://bit.ly/43ko8RD">BLOGSPOT</a>
<a href="https://bit.ly/44hZEJV">BLOGSPOT</a>
<a href="https://bit.ly/3JPSg0t">super4k</a>
