### ISSUE TITLE
compute_mIoU for SCNN 

### ISSUE THREAD

**Issue by BoSeal** [XingangPan/SCNN#100]
您好！请问在Cityscapes上使用SCNN进行语义分割时，如何计算模型的精度，即IOU？是否需要我新建一个py文件，在里面计算IOU？还是说可以直接在SCNN代码中进行少量的代码修改，就可以直接计算出IOU？

**Comment by XingangPan** [comment]
@BoSeal This repo is for lane detection, and the evaluation code for segmentation is not provided. You may check these repos for computing IOU: 
https://github.com/hszhao/semseg
https://github.com/hszhao/PSPNet
https://github.com/CSAILVision/semantic-segmentation-pytorch
