### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by BoSeal** [XingangPan/SCNN#103]
@XingangPan ,你好，基于Cityscapes训练SCNN时，我是否可以通过对SCNN代码进行修改后，直接使用彩色的图像作为label？如下所示：
![图片](https://user-images.githubusercontent.com/39556913/72682191-79a5b680-3b05-11ea-9261-7ddb0070fe9e.png)

**Comment by XingangPan** [comment]
No, you can't. Please use train_id label.
