### ISSUE TITLE
Is there a PyTorch implementation of SCNN?

### ISSUE THREAD

**Issue by nisha1729** [XingangPan/SCNN#117]
You've given a link to the TensorFlow implementation. So I was wondering if you have one in PyTorch as well.

**Comment by XingangPan** [comment]
Sorry we don't have pytorch version of SCNN yet. But this link https://github.com/cardwing/Codes-for-Lane-Detection also has a pytorch implementation for another method ERFNet, which might be helpful.

**Comment by nisha1729** [comment]
Yes, I saw that one. Thanks!
