### ISSUE TITLE
Experiment issue

### ISSUE THREAD

**Issue by zj040045** [XingangPan/SCNN#12]
The experiment results in the paper are lane marking detection results. I wonder whether you tried to segment lane area directly?

**Comment by XingangPan** [comment]
No. Our model gives probability maps like in semantic segmentation, and post-processing is applied to predict lane lines. However, If you want to segment lane area, it is natural to use the probability map to generate it.

**Comment by zj040045** [comment]
@XingangPan And how can I convert annotations to labels? I find that the dataset does not contain test image labels.

**Comment by XingangPan** [comment]
In our experiments segmentation labels for test images are not needed. But if you need that, I'll release annotation processing code after ECCV ddl : )

**Comment by XingangPan** [comment]
Test image labels are now provided in the Google drive dataset folder.

**Comment by XingangPan** [comment]
@zj040045 The code for generating per-pixel labels from raw annotations is now provided at https://github.com/XingangPan/seg_label_generate
