### ISSUE TITLE
lane markings annotation

### ISSUE THREAD

**Issue by lldmrc** [XingangPan/SCNN#13]
Hi, 
firstly thanks for sharing code and dataset.
I have a question regarding the lane markings annotation.
In the paper and website images the lane markings are highlighted with 4 different colours.
Green and red for left/right egolane bound, blue for left lane and yellow for right lane.
In the dataset .txt annotation files thought there's just a list of points for each line but I didn't found any information regarding the line type (ego left bound , ego right bound etc.).
Is this stored somewhere or I need to recover it by myself with some position assumption?
Thanks

**Comment by XingangPan** [comment]
You need to recover it with line slope.
By the way, I may release annotation processing code after ECCV ddl : )
