### ISSUE TITLE
dataset explaning

### ISSUE THREAD

**Issue by DanlanChen** [XingangPan/SCNN#16]
Hello, Xingan, 
I am wondering if you could make a detailed explanation about the dataset you provided, I noticed you explained it in https://xingangpan.github.io/projects/CULane.html, I am wondering what is the 00120.line.txt mean for each image?
And why is the image in laneseg_label_w16 all black?

**Comment by XingangPan** [comment]
1. Each xxxxx.line.txt is the annotation file for the image xxxxx.jpg.
In the annotation file, each line gives the x,y coordinates for key points of a lane marking.
2. The images in laneseg_label_w16 are all black because the pixel values are around 0-4, (0 for background, 1-4 for four lane markings.) So it looks black in 0-255 images.

**Comment by suphy2009** [comment]
Hi, Xingang
What do the last four number of each line mean in the dataset list/train_gt.txt file?  How are they labeled? 
Such as this line:
/driver_182_30frame/06011140_0164.MP4/03810.jpg /laneseg_label_w16/driver_182_30frame/06011140_0164.MP4/03810.png 0 1 1 0

In addition, how should these four numbers be used in training?

**Comment by ytzhao** [comment]
@XingangPan Hi, Xingang, I cropped some of the CULane images and resize them to the original size 590x1640, but without providing the xxx.line.txt files. The error occurs as following at line 102 of dataload.lua. But I could not find where you used these files. Could you please point out how do you use files? Thank you.

**Comment by suphy2009** [comment]
@XingangPan What is the difference between the last four numbers, such as 1 1 1 0 and 0 1 1 1 ?

**Comment by XingangPan** [comment]
@ytzhao  The code for generating per-pixel labels from raw annotations is now provided at https://github.com/XingangPan/seg_label_generate

**Comment by ytzhao** [comment]
@XingangPan Thank you very much, I'll have a try :)

**Comment by csu-xiewei** [comment]
The seg of your dataset is an image of one channel, but your SCNN output is a four channel image. When I train, Err1 Nan

**Comment by XingangPan** [comment]
@suphy2009 
We care about 4 lane markings: 2 on the left and 2 on the right.
1 1 1 0 means you have 2 lane markings on the left, one lane marking on the right.
0 1 1 1 means you have 1 lane marking on the left, two lane markings on the right.

**Comment by disheet** [comment]
@XingangPan Can you tell which you are following to save annotation data?
Is it COCO , YOLO or something else?
