### ISSUE TITLE
about the result

### ISSUE THREAD

**Issue by cuicuizhang1989** [XingangPan/SCNN#17]
| Test: [6][59/807] Err 0.16707 (0.17657) Err 0.05300 (0.04383) Acc 94.77 (94.820) mRec 67.03 (67.790) mIOU 47.87 (41.304)	
 | Test: [6][60/807] Err 0.19414 (0.17686) Err 0.04501 (0.04385) Acc 94.45 (94.814) mRec 62.64 (67.704) mIOU 38.60 (41.259)	

is the training result right?

**Comment by XingangPan** [comment]
Seems right. You may also use evaluation code in tools to see if the F-measure matches with our rights.
