### ISSUE TITLE
make error in lane_evaluation

### ISSUE THREAD

**Issue by trooperli** [XingangPan/SCNN#23]
When I do make for the lane_evaluation, folder, I got the following error:

`src/evaluate.cpp: In function ‘void visualize(std::__cxx11::string&, std::vector<std::vector<cv::Point_<float> > >&, std::vector<std::vector<cv::Point_<float> > >&, std::vector<int>, int)’:
src/evaluate.cpp:236:59: error: ‘line’ was not declared in this scope
    line(img, p_interp[n], p_interp[n+1], color, width_lane);
                                                           ^
src/evaluate.cpp:271:59: error: ‘line’ was not declared in this scope
    line(img, p_interp[n], p_interp[n+1], color, width_lane);
`

My opencv version is 2.4.9.1. Can someone please help me take a look?

Thanks,
Greg

**Comment by ytzhao** [comment]
@trooperli Hi, you may try to do like this:
1. in `src/lane_compare.cpp`, find line 43 and line 47
2. change `line(...)` to 'cv::line(...)'
3. in `include/lane_compare.hpp`
4 add 
```cpp
#include <opencv2/core/core.hpp>
#include <opencv2/imgproc.hpp>
```
5. make again 

Hope this method could help you :)

**Comment by trooperli** [comment]
Thanks ytzhao! It is working for me.

**Comment by chenyiman** [comment]
@ytzhao Hello, my opencv version is 3.4.1 and I met the same error, do you know how to solve it?

**Comment by Neha-swan** [comment]
CXX src/evaluate.cpp
src/evaluate.cpp: In function ‘void visualize(std::string&, std::vector<std::vector<cv::Point_<float> > >&, std::vector<std::vector<cv::Point_<float> > >&, std::vector<int>, int)’:
src/evaluate.cpp:236:59: error: ‘line’ was not declared in this scope
    line(img, p_interp[n], p_interp[n+1], color, width_lane);
                                                           ^
src/evaluate.cpp:271:59: error: ‘line’ was not declared in this scope
    line(img, p_interp[n], p_interp[n+1], color, width_lane);
                                                           ^
Makefile:35: recipe for target 'build/src/evaluate.o' failed
make: *** [build/src/evaluate.o] Error 1



This is my error ##URGENT #urgent  

open cv version   3.4.1  please help

**Comment by Neha-swan** [comment]
WHEN i run make file with those chnages in BOTH EVALUATE and COMPARE fiiles....my error was

CXX src/evaluate.cpp
CXX src/lane_compare.cpp
CXX/LD evaluate
/usr/bin/ld: cannot open output file evaluate: Is a directory
collect2: error: ld returned 1 exit status
Makefile:39: recipe for target 'evaluate' failed
make: *** [evaluate] Error 1

**Comment by SangDooLee** [comment]
@Neha-swan 
I had the same issue.
by Searching Google, I just found that 
at  ../tools/lane_evaluation gedit Makefile       

and then find 

LIBRARIES += opencv_core opencv_highgui opencv_imgproc

edit like this 

LIBRARIES += opencv_core opencv_highgui opencv_imgproc opencv_imgcodecs
