### ISSUE TITLE
Does your CULane data have on Baidu cloud disk? 

### ISSUE THREAD

**Issue by xtanitfy** [XingangPan/SCNN#24]
The 20G file cannot be downloaded.Or do you have other places that you can store without going over the wall?

**Comment by XingangPan** [comment]
@xtanitfy The dataset is now available at https://pan.baidu.com/s/19VmfhPQqbKWijsyRAdq7DQ (password: mqg9)

**Comment by xtanitfy** [comment]
Thanks very much！
