### ISSUE TITLE
cudnnFindConvolutionBackwardDataAlgorithm failed

### ISSUE THREAD

**Issue by xtanitfy** [XingangPan/SCNN#25]
My error log as follow on training:

=> Training epoch # 1	

cudnnFindConvolutionBackwardDataAlgorithm failed: 	2	 convDesc=[mode : CUDNN_CROSS_CORRELATION datatype : CUDNN_DATA_FLOAT] hash=-dimA4,128,144,400 -filtA128,128,3,3 4,128,144,400 -padA1,1 -convStrideA1,1 CUDNN_DATA_FLOAT	
/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 11 module of nn.Sequential:
/root/torch/install/share/lua/5.1/cudnn/find.lua:483: cudnnFindConvolutionBackwardDataAlgorithm failed, sizes:  convDesc=[mode : CUDNN_CROSS_CORRELATION datatype : CUDNN_DATA_FLOAT] hash=-dimA4,128,144,400 -filtA128,128,3,3 4,128,144,400 -padA1,1 -convStrideA1,1 CUDNN_DATA_FLOAT
stack traceback:
	[C]: in function 'error'
	/root/torch/install/share/lua/5.1/cudnn/find.lua:483: in function 'backwardDataAlgorithm'
	...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:209: in function 'updateGradInput'
	/root/torch/install/share/lua/5.1/nn/Module.lua:31: in function </root/torch/install/share/lua/5.1/nn/Module.lua:29>
	[C]: in function 'xpcall'
	/root/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/root/torch/install/share/lua/5.1/nn/Sequential.lua:84: in function 'backward'
	./train.lua:74: in function 'train'
	main.lua:51: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	/root/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	/root/torch/install/share/lua/5.1/nn/Sequential.lua:84: in function 'backward'
	./train.lua:74: in function 'train'
	main.lua:51: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

**Comment by xtanitfy** [comment]
I  find a solution at https://github.com/jcjohnson/fast-neural-style/issues/93.
After setting batch_size=2,the training ERR will be NAN.I use only one 1080TI,maybe I should be upgrade the hardware,or do you have other ways?

**Comment by xtanitfy** [comment]
I Roughly solved this problem by changing lr=0.001.

**Comment by XingangPan** [comment]
@xtanitfy I train it with 4 TITANX GPUs. It takes no more than one day for 60000 iterations. You may reduce the epochs.

**Comment by xtanitfy** [comment]
Do you only need to train less than 10 epochs to converge?I follow your calculations: 
n_epoch = 60000*12/88880.=8.10

**Comment by XingangPan** [comment]
Yes, your calculation is right. Since the dataset is densely extracted from videos, you may not need too much epochs.

**Comment by xtanitfy** [comment]
Thanks！
