### ISSUE TITLE
Annotation issues

### ISSUE THREAD

**Issue by OneMondy** [XingangPan/SCNN#27]
Hi,xingang

I am wondering about the colors of the annotation lines,can you tell me if there have some rules about the color of the lines? I found the blue lines is always on the left and the green line is on the side of it.Besides,the lines  converge to one point,I am think about if this is necessary. Moreover,can you tell me some issues about the annoation?Finally ,Can you tell me the labeling tool if it is convenient?

Thanks!

**Comment by OneMondy** [comment]
@XingangPan

**Comment by XingangPan** [comment]
@OneMondy We care about 4 lane markings: 2 on the left and 2 on the right. 
During visualization, we use blue, green, red, yellow for these four lane markings.
The lines are not necessarily converged to one point. There are cases that they do not converge.
Unfortunately we cannot provide the labeling tool, which is for commercial use.

**Comment by OneMondy** [comment]
@XingangPan thank you for your reply！
