### ISSUE TITLE
How to get the visualized lane prediction.

### ISSUE THREAD

**Issue by zhangguangyuan0001** [XingangPan/SCNN#28]
@XingangPan matlab -nodisplay -r "main;exit"  # or you may simply run main.m from matlab interface, the line coordinates are generated.But How can I get a visualized lane prediction curve in the source  image, can you give me some advice and help?

**Comment by XingangPan** [comment]
@zhangguangyuan0001 At tools/lane_evaluate/run.sh, add a '-s' option, then run the script. You should be able to see the visualization.

**Comment by YilmazOrkun** [comment]
@XingangPan where do I add the '-s' option? In the script or in terminal when running run.sh?

**Comment by XingangPan** [comment]
@YilmazOrkun In the script.

**Comment by JacobleeDJI** [comment]
> @XingangPan where do I add the '-s' option? In the script or in terminal when running run.sh?
root=../../
data_dir=${root}data/CULane/
exp=vgg_SCNN_DULR_w9
detect_dir=${root}tools/prob2lines/output/${exp}/
w_lane=30;
iou=0.5;  # Set iou to 0.3 or 0.5
im_w=1640
im_h=590
frame=1
list=${data_dir}list/test.txt
out=./output/${exp}_iou${iou}.txt
**./evaluate -a $data_dir -d $detect_dir -i $data_dir -l $list -w $w_lane -t $iou -c $im_w -r $im_h -f $frame -o $out###  _-s_**
Is it like this? Which file is the visualization effect save path in? thx a lot~

**Comment by JacobleeDJI** [comment]
> @YilmazOrkun In the script.

./evaluate -a $data_dir -d $detect_dir -i $data_dir -l $list -w $w_lane -t $iou -c $im_w -r $im_h -f $frame -o $out### _-s_
Seniors, is this the case? Will the effect display output images or MATLAB display?
