### ISSUE TITLE
About the text issues

### ISSUE THREAD

**Issue by OneMondy** [XingangPan/SCNN#29]
Hi xingang,
    Can I think that running test.sh is to identify the image below the test.txt path? I deleted some of the pictures listed in the test.txt file and found that the generated results are the same as those not deleted. This feels conflicting. Can you help me solve this problem?

Thank you.

**Comment by OneMondy** [comment]
@XingangPan

**Comment by XingangPan** [comment]
Have you generate the results of those pictures before you delete them in the list? 
If so, you should delete the results before you run a second test. 
Or, you may change the save path to save the results in a new folder.

**Comment by XingangPan** [comment]
@OneMondy I see the problem. If you have changed your data list, you should remove the files in folder 'gen' before run experiments.

**Comment by OneMondy** [comment]
@XingangPan I deleted the generated file according to your prompts, and deleted some of the test.txt inside the path, re-run, find and not delete the path to run the same result.
Are you referring to the uncomment ‘rm gen/lane.t7’?What is the role of this? and When I run ,it prompts ‘ cannot remove 'gen/lane.t7': No such file or directory’
