### ISSUE TITLE
About the pretrained model.

### ISSUE THREAD

**Issue by gjy3035** [XingangPan/SCNN#3]
The readme.md says that the pertrained model is trained on ImageNet.
However, loading it in the code, I find its architecture is not a classification.

**Comment by XingangPan** [comment]
Hi, sorry to reply late. 
The architecture of the pretrained model is modified for lane detection, thus is different from the original classification model. But the initial weight of its first 13 convolution layers are copied from VGG16 pretrained on ImageNet. Hope this answers your question.
