### ISSUE TITLE
test.sh

### ISSUE THREAD

**Issue by chenyiman** [XingangPan/SCNN#30]
![1526394858 1](https://user-images.githubusercontent.com/39306863/40063572-3a13fe5e-5890-11e8-9a83-79c3cc633284.png)
I met such error when I tried to test, could you give me some advice? Thanks~

**Comment by chenyiman** [comment]
If I change "th" in test.sh to "sh", the error is as below:
![1526395308 1](https://user-images.githubusercontent.com/39306863/40064343-e33ac548-5891-11e8-9a67-d8721a732960.png)

**Comment by DanLiu0623** [comment]
@chenyiman 应该是你没有正确安装torch导致的，按照这个链接http://torch.ch/docs/getting-started.html安装torch，然后这个链接中提到的cudnn安装办法安装cudnn4或者cudnn5，我安装的是cudnn5，https://github.com/facebook/fb.resnet.torch.
