### ISSUE TITLE
What is the development platform

### ISSUE THREAD

**Issue by cuicuizhang1989** [XingangPan/SCNN#4]
is Linux ubuntu? Is there a requirement for the version of MATLAB？ and A link to the installation of software can be provided if you can , thanks a lot.

**Comment by XingangPan** [comment]
Yes the development platform is ubuntu (v14.04). I use MATLAB R2014a, but it should also work with later version. For torch, the installation link is given in README.md, and to install opencv, this might be useful https://docs.opencv.org/2.4/doc/tutorials/introduction/linux_install/linux_install.html
