### ISSUE TITLE
nonlinear activation and pretrained vgg

### ISSUE THREAD

**Issue by gexiaosulynn** [XingangPan/SCNN#50]
@XingangPan hello,thank you for your code.I have some questions.
1、I want to know whether each slice need nonlinear activation as the paper said ，I only found convolution opreration of each slice from your code.
2、Why your pretrained vgg had dilation convolution layer，whether  the pretrained vgg was your own trained model on ImageNet，not the  opened pretrained  weights trained by others.
3.  I was confused about the train step. If I need train the vgg first, then insert the scnn. I  train the vgg which had included scnn derectly now.

**Comment by XingangPan** [comment]
1. Each slice need nonlinear activation. Sorry that the original code is wrong. I have fix that in commit "Fix error in SCNN-gen.lua".
2. We have modified the VGG model for lane detection.
3. Please use the updated code to generate vgg+SCNN, this problem should not occur.
