### ISSUE TITLE
Try to train on the tusimple dataset

### ISSUE THREAD

**Issue by passion3394** [XingangPan/SCNN#54]
@XingangPan @sanskar107 Thanks for your great work.

I use the SCNN-gen.lua file to generate my own network for tusimple dataset. But I got the following error, I have find everywhere on the search engine or GitHub, but no answer given, could you help me to solve it, thanks ahead!!!
[SCNN-gen.txt](https://github.com/XingangPan/SCNN/files/2467872/SCNN-gen.txt)

/usr/local/bin/luajit: /usr/local/share/lua/5.1/nn/THNN.lua:110: weight tensor should be defined either for all or no classes at /tmp/luarocks_cunn-scm-1-1602/cunn/lib/THCUNN/generic/SpatialClassNLLCriterion.cu:28
stack traceback:
[C]: in function 'v'
/usr/local/share/lua/5.1/nn/THNN.lua:110: in function 'SpatialClassNLLCriterion_updateOutput'
/usr/local/share/lua/5.1/nn/SpatialClassNLLCriterion.lua:43: in function 'updateOutput'
...cal/share/lua/5.1/cudnn/SpatialCrossEntropyCriterion.lua:37: in function 'updateOutput'
./ParallelCriterion2.lua:28: in function 'forward'
./train.lua:71: in function 'train'
main.lua:51: in main chunk
[C]: in function 'dofile'
/usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
[C]: at 0x00405f70

**Comment by passion3394** [comment]
Have solved the problem. So I will close the issue.

**Comment by yoga-0125** [comment]
> Have solved the problem. So I will close the issue.

May I ask how do you update files in SCNN/tools/lane_evaluation for TuSimple data evaluation?

Thanks a lot!
