### ISSUE TITLE
Error generating per-pixel labels 

### ISSUE THREAD

**Issue by zzz1515151** [XingangPan/SCNN#77]
Hi, 
i download the CULane dataset from https://xingangpan.github.io/projects/CULane.html but found all black images in dir /laneseg_label_w16. i also tried generating scrips from https://github.com/XingangPan/seg_label_generate and got also all black images. Did anyone face the same problem or where can i get the correct seg image? 
Thanks in advance!

**Comment by XingangPan** [comment]
@zzz1515151 All black images are correct. Because they are label map with small label value like 0,1,2,3,4, which would look like black on 255 scale png images.

**Comment by zzz1515151** [comment]
oo, i didn't see these labels carefully. Thanks for you reply.
