### ISSUE TITLE
Evaluation from tensorflow implementation

### ISSUE THREAD

**Issue by zguo008** [XingangPan/SCNN#78]
Hi:)

I re-implemented your code from @cardwing's tensorflow version.

However, it's a bit troublesome for me to evaluate the result from there.

Could you please tell me the format of the txt file in the output folder in prob2line folders? 

Also may I know how should I arrange my result probmap picture so that it can fit into this evaluation script:)

Best regards,

ZX

**Comment by XingangPan** [comment]
The txt file should have the same format as the original annotation files of the CULane dataset. 
Specifically, for a txt file, each line gives the x,y coordinates for key points of a lane marking.

**Comment by zguo008** [comment]
Thank you!!
