### ISSUE TITLE
Evaluation matrix with different size probmap

### ISSUE THREAD

**Issue by zguo008** [XingangPan/SCNN#80]
Hi,

These days I have changed the train_img_height and width to (256,512) so that it can fit in my graphic cards memory. So I wonder how I can adjust the evaluation script accordingly? The origin output prob map is of size (288,800) and search for local maxima every 20 rows(20 in orginal size,20*img_height/288 in out_prob_map) for 18 iterations. So basically it means you search 360 rows out of 590 rows in original image. 

I wonder how you get the number 18? Do I need to change this number if I have a different sized output prob map?

Best,

ZX

**Comment by XingangPan** [comment]
@zguo008 A simple adjustment is to interpolate your output prob map to (288x800) before saving them so that you don't need to change other evaluation scripts. 
The number 18 is a rough estimation according to the training set, as lane markings are not likely to show up on the sky.

**Comment by zguo008** [comment]
Thank you, I read the code carefully again just now.
I think I can modify the code like this in getlane.m:
for i=1:18
    lineId = uint16(256-(i-1)*20/590*256); basically change 288 to 256 and change the width parameter in main.m accordingly.
But anyway, thank you for your reply:)

Have a nice day.

Cheers,

ZX
