### ISSUE TITLE
Will the sequence of SCNN_D, SCNN_U, SCNN_R, SCNN_L effect the performance？

### ISSUE THREAD

**Issue by chixma** [XingangPan/SCNN#87]
As the lanes in the datasets usually appear in a vertical-like mode, I am not sure whether the sequence of SCNN_D, SCNN_U, SCNN_R, SCNN_L effects the performance? Do you have any idea about it?

**Comment by XingangPan** [comment]
@chixma I haven't tried a different sequence. But I guess it won't make much difference.
