### ISSUE TITLE
What‘s the standard of labeling the lanes？

### ISSUE THREAD

**Issue by yeyewen** [XingangPan/SCNN#88]
@XingangPan  If we got three lane markings ，how do we label the data ？0111 or 1110 ，if we got five lanes markings or more? You mentioned  that you care about  4 lane markings, if we got five or more ,how do we choose the four?

**Comment by XingangPan** [comment]
@yeyewen [0,1,1,1] means there is 1 lane on the left and 2 lanes on the right, [1,1,1,0] means there are 2 lanes on the left and 1 lane on the right. Left or right is decided by the slope of the lane.
We only care about two lane markings for each side (left or right). For example if you have 2 lane markings on the left and 3 lane markings on the right. We would ignore the most right one.

**Comment by yeyewen** [comment]
@XingangPan Thanks！You mentioned that 9 scenarios are collected in your paper. I am interested
 in you work.If I want to pick out the dazzle light picture，what should I do ? What  if I pick out other scenarios？

**Comment by XingangPan** [comment]
@yeyewen You can download our dataset. You can find a list folder in the dataset, under the folder you can find the image list for each category.

**Comment by yeyewen** [comment]
@XingangPan Thanks!
![image](https://user-images.githubusercontent.com/37136363/65824357-32679180-e29a-11e9-9e0d-c58773715f3f.png) The list folder just contains the test_split.Do you have the train_split?The test set may be too small for me .
