### ISSUE TITLE
CULane Data Set - Empty folders

### ISSUE THREAD

**Issue by GreatGameDota** [XingangPan/SCNN#91]
I tried downloading the data set (from https://drive.google.com/drive/u/0/folders/1mSLgwVTiaUMAb4AVOWwlCD5JcWdrwpvu) and I downloaded driver_161_90frame.tar.gz but when I open it 4 folders are empty:
EDIT: I looked at the photos before and after the files and I think they were just deleted because its just a car sitting parked. Confused though because there's label images for all of those deleted photos
EDIT 2: Ok the two folders before and after are also missing images, I'm guessing it's just to censor something so this is just a PSA for anyone using the data set
<img width="489" alt="Annotation 2019-10-09 101721" src="https://user-images.githubusercontent.com/17858650/66495352-bf6ecf80-ea7e-11e9-8207-0a5e4f4be72c.png">
<img width="490" alt="Annotation 2019-10-09 101828" src="https://user-images.githubusercontent.com/17858650/66495375-c72e7400-ea7e-11e9-94ab-908c73a1a0ad.png">
<img width="488" alt="Annotation 2019-10-09 102120" src="https://user-images.githubusercontent.com/17858650/66495391-cac1fb00-ea7e-11e9-8979-24c63e848f7d.png">
<img width="490" alt="Annotation 2019-10-09 102140" src="https://user-images.githubusercontent.com/17858650/66495400-ceee1880-ea7e-11e9-81c9-282cd3228876.png">
<img width="488" alt="Annotation 2019-10-09 102202" src="https://user-images.githubusercontent.com/17858650/66495421-d31a3600-ea7e-11e9-8dec-f9af5cc3ad79.png">

**Comment by XingangPan** [comment]
@GreatGameDota Those images should be deleted deliberately when we built the dataset due to bad image quality, and are not in the training list.

**Comment by GreatGameDota** [comment]
> @GreatGameDota Those images should be deleted deliberately when we built the dataset due to bad image quality, and are not in the training list.

Thanks for the reply! In the label file there are still images in these files even though there is no training image to train on.
