### ISSUE TITLE
Wrong size in annotations

### ISSUE THREAD

**Issue by lmameri** [XingangPan/SCNN#92]
Hi,
 This doesn't raise any issue but I was wondering why even if the size of the pictures and/or laneseg_label is 1640x590, some of the annotations coordonates goes higher than 1640 ? For example in _Dataset CULane/dataset/driver_23_30frame/05151640_0419.MP4/00000.lines_, 3rd line, first coordonate :
 **1660.47** 470.
 Is it because the lines were interpolated ?
Thank you !

**Comment by XingangPan** [comment]
@lmameri Yes, it is caused by spline fitting, and should not matter much.
