### ISSUE TITLE
SCNN about semantic segmentation on Cityscapes

### ISSUE THREAD

**Issue by BoSeal** [XingangPan/SCNN#95]
@XingangPan , 1、What is the size of the input image of SCNN on Cityscapes ?  is 288 X 800 ??
    2、Cityscapes  Lables：标签是需要以下两个，还是只需要提供gtFine_labelTrainIds.png 就可以了？
![图片](https://user-images.githubusercontent.com/39556913/71258446-23601f00-2371-11ea-965b-2828ee93731a.png)

**Comment by XingangPan** [comment]
@BoSeal 1. For cityscapes, we use random crop to the training images, the crop size is 713x713.
2. Only gtFine_labelTrainIds.png is needed.

**Comment by BoSeal** [comment]
好的，非常感谢！
