### ISSUE TITLE
关于SCNN数据集问题

### ISSUE THREAD

**Issue by BoSeal** [XingangPan/SCNN#96]
@XingangPan ,CULane数据集中，laneseg_label_w16文件中所有图片都是黑色的，如下所示：
![图片](https://user-images.githubusercontent.com/39556913/71305334-2f012380-240d-11ea-9041-c7d3b2f6cd55.png)

之后，我又检查了下train_gt.txt，里面的路径，如下所示：
![图片](https://user-images.githubusercontent.com/39556913/71305347-5952e100-240d-11ea-8841-d9a9bd110e3d.png)

我理解的是，laneseg_label_w16文件中的图片，应该是包含4条车道线+背景，但事实上我看到的都是背景，不包含车道线，所以我猜测，laneseg_label_w16文件中的图片是不是有问题？还是说，我理解错了？麻烦您可以为我答疑么？

**Comment by XingangPan** [comment]
@BoSeal 背景是0,四条车道线分别是1,2,3,4，他们在0-255通道的png图片下看起来就都是黑色的。

**Comment by BoSeal** [comment]
I see，thanks！
