### ISSUE TITLE
SCNN on Cityscapes

### ISSUE THREAD

**Issue by BoSeal** [XingangPan/SCNN#98]
![图片](https://user-images.githubusercontent.com/39556913/71308958-612a7980-243d-11ea-8c04-e102d07f4b1f.png)
您好！请问：**这里的随机裁剪（random crop）方法的目的是什么：**

1. **目的1：**猜测：它是作为数据增强(Data Augmentation)方式，通过这种操作，我们可以获得更多的图片样本，原来的一张图片可以变为多张图片，扩大样本容量。
**问题1：**如果使用random crop的目的是：上述目的1，那么这样裁剪后，图片数量就增多了，那么就会出现Label图片数量和原始图像数量不一样的情况，且二者的size也不一样，这样的话，我如何用Label去训练？

2. **目的2：**猜测：可能是在做实验的时候，您考虑到原始图片（1024 X 2048）太大，所以使用random crop方法，对每张原始图片只随机裁剪出相对应的**一张小图片（713 X 713）**，然后将这张小图片作为输入，进行模型训练？但这样的话，Label图片和输入图片的size不一样，这样可以训练模型么？

因为我是初学者，不太清楚图像语义分割模型是如何训练的，有哪些注意事项，所以麻烦您可以为我答疑，谢谢！

**Comment by XingangPan** [comment]
@BoSeal 对输入图片做random crop的同时，会对label做相同的random crop，所以二者数量和size一样。
你提到的1,2目的都对，既是data augmentation也是减少显存。

**Comment by BoSeal** [comment]
thank you very much
